"""
Default configuration constants and parameter definitions for the MfsFlow pipeline.

This module defines the default configuration structure and parameters used
throughout the MfsFlow analysis pipeline, including sample settings,
reference files, filtering thresholds, and pipeline options.
"""

# Default configuration structure
DEFAULT_CONFIG = {
    "project": "",  # Will be set from command line
    "sample": {
        "sample_type": "auto",      # Overridden by --manual/--plate/--expectBarcode/--discoverBarcodes
        "sample_id": "1"            # Overridden by --manual/--plate
    },
    "sequence_files": {
        "file1": {
            "name": "",             # Will be set from --fastq
            "base_definition": []   # Will be calculated based on read length
        },
        "file2": {
            "name": "",             # Will be set from --fastq
            "base_definition": []   # Will be calculated based on read length
        }
    },
    "reference": {
        "STAR_index": "",           # Will be set from --genomeDir
        "GTF_file": "",             # Will be detected in --genomeDir
        "additional_files": None,
        "additional_STAR_params": "--clip3pAdapterSeq CTGTCTCTTATACACATCT"
    },
    "out_dir": "",                  # Will be set to current_dir/sample_name
    "num_threads": 30,              # Will be set from --threads
    "filter_cutoffs": {
        "BC_filter": {
            "num_bases": 4,
            "phred": 5
        },
        "UMI_filter": {
            "num_bases": 3,
            "phred": 5
        }
    },
    "barcodes": {
        "barcode_num": None,
        "automatic": False,
        "BarcodeBinning": 1,
        "nReadsperCell": 1,
        # barcode_file will be generated by the pipeline logic
        "barcode_file": "" 
    },
    "counting_opts": {
        "introns": True,
        "strand": 1,
        "internal_strand": 0,
        "Ham_Dist": 1,
        "twoPass": False,
        "gene_body_max_reads": 5000000,
        "gene_body_sample_seed": 42
    },
    "performance_opts": {
        "stream_bc_correction": True,
        "tmp_root": None
    },
    "make_stats": True,
    "make_h5ad": True,
    "make_sorted_bam": True,
    "make_ub_bam": False,
    "which_Stage": "Filtering",
    "toolkit_directory": ".",       # Will be resolved relative to script
    "read_layout": "PE"             # Default PE, verified by script
}
